name: Create Release and Attach Artifacts

on:
  push:
    tags:
      - "v*.*.*" # Trigger when a tag with this format is pushed
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release (e.g., v1.2.3)"
        required: false
        default: ""
      release_name:
        description: "Release name (default: derived from tag)"
        required: false
        default: ""

jobs:
  create-release:
    name: Create GitHub Release and Attach Artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_package
        with:
          python-version: "3.9"

      - name: Determine Tag Name
        id: determine_tag
        run: |
          if [[ "${{ github.event.inputs.tag_name }}" != "" ]]; then
            echo "::set-output name=tag_name::${{ github.event.inputs.tag_name }}"
          elif [[ "${{ github.ref }}" != "" ]]; then
            echo "::set-output name=tag_name::${{ github.ref_name }}"
          else
            echo "Error: No tag name provided." >&2
            exit 1
          fi

      - name: Determine Release Name
        id: determine_release_name
        run: |
          if [[ "${{ github.event.inputs.release_name }}" != "" ]]; then
            echo "::set-output name=release_name::${{ github.event.inputs.release_name }}"
          else
            echo "::set-output name=release_name::Release ${{ steps.determine_tag.outputs.tag_name }}"
          fi

      - name: Create GitHub Release
        id: create_release
        run: |
          gh release create ${{ steps.determine_tag.outputs.tag_name }} ./dist/* \
            --title "${{ steps.determine_release_name.outputs.release_name }}" \
            --notes "ğŸ‰ New release: ${{ steps.determine_tag.outputs.tag_name }}" \
            --draft=false \
            --prerelease=false
        env:
          GH_TOKEN: ${{ github.token }}
